[package]
name = "rs-primitives2rbat"
version = "0.1.0"
edition = "2024"

[dependencies.serde]
version = "1"
default-features = false
features = [
	"std",
	"derive",
]

[dependencies.rs-ints2arrow]
version = "0"
default-features = false
features = [
	"sync",
	"fs",
]
