[package]
name = "primitives2rbat"
version = "0.1.0"
edition = "2024"

[dependencies.rs-primitives2rbat]
path = "../.."

[dependencies.serde_json]
version = "1"
default-features = false
features = [
	"std",
]
